export const orderList=[
        {
          "productId": "CLOTH001",
          "productName": "Casual T-Shirt",
          "category": "Clothes",
          "quantity": 2,
          "price": 25.00,
          "description": "Comfortable and stylish casual t-shirt made from soft cotton fabric.",
          "status": "Delivered",
          "orderDate": "2023-08-13",
          "totalAmount": 50.00,
        },
        {
          "productId": "CLOTH002",
          "productName": "Slim Fit Jeans",
          "category": "Clothes",
          "quantity": 1,
          "price": 50.99,
          "description": "Modern slim fit jeans with a touch of stretch for flexibility and comfort.",
          "status": "Processing",
          "orderDate": "2023-08-13",
          "totalAmount": 50.99,
        },
        {
          "productId": "CLOTH003",
          "productName": "Elegant Floral Dress",
          "category": "Clothes",
          "quantity": 1,
          "price": 150.75,
          "description": "A beautiful floral dress perfect for special occasions or a night out.",
          "status": "Shipped",
          "orderDate": "2023-08-13",
          "totalAmount": 150.75,
        },
        {
          "productId": "CLOTH004",
          "productName": "Stylish Leather Jacket",
          "category": "Clothes",
          "quantity": 1,
          "price": 100.00,
          "description": "Classic leather jacket with a modern twist, perfect for colder months.",
          "status": "Processing",
          "orderDate": "2023-08-13",
          "totalAmount": 300.00,
        },
        {
          "productId": "CLOTH005",
          "productName": "Printed Mini Skirt",
          "category": "Clothes",
          "quantity": 2,
          "price": 50.00,
          "description": "Playful and trendy printed mini skirt for a fun fashion statement.",
          "status": "Processing",
          "orderDate": "2023-08-13",
          "totalAmount": 300.00,
        },
        {
          "productId": "CLOTH006",
          "productName": "Cozy Knit Sweater",
          "category": "Clothes",
          "quantity": 1,
          "price": 150.50,
          "description": "Warm and cozy knit sweater with a relaxed fit, perfect for chilly days.",
          "status": "Cancelled",
          "orderDate": "2023-08-12",
          "totalAmount": 250.50,
        },
        {
          "productId": "CLOTH007",
          "productName": "Formal Dress Shirt",
          "category": "Clothes",
          "quantity": 1,
          "price": 100.00,
          "description": "Elegant and crisp dress shirt suitable for formal occasions.",
          "status": "Cancelled",
          "orderDate": "2023-08-12",
          "totalAmount": 250.50,
        },
        {
          "productId": "CLOTH008",
          "productName": "Summer Shorts",
          "category": "Clothes",
          "quantity": 1,
          "price": 75.25,
          "description": "Lightweight and comfortable shorts for a casual summer look.",
          "status": "Shipped",
          "orderDate": "2023-08-11",
          "totalAmount": 125.25, 
        },
        {
          "productId": "CLOTH009",
          "productName": "Colorful Patterned Socks",
          "category": "Clothes",
          "quantity": 2,
          "price": 25.00,
          "description": "Playful and vibrant patterned socks to add a pop of color to your outfit.",
          "status": "Shipped",
          "orderDate": "2023-08-11",
          "totalAmount": 125.25, 
        },
        {
          "productId": "CLOTH010",
          "productName": "Classic Fedora Hat",
          "category": "Clothes",
          "quantity": 1,
          "price": 30.99,
          "description": "Timeless and stylish fedora hat to complete your look.",
          "status": "Delivered",
          "orderDate": "2023-08-10",
          "totalAmount": 180.99,
        },
        {
          "productId": "CLOTH011",
          "productName": "Winter Gloves",
          "category": "Clothes",
          "quantity": 2,
          "price": 75.00,
          "description": "Warm and cozy winter gloves to keep your hands protected from the cold.",
          "status": "Delivered",
          "orderDate": "2023-08-10",
          "totalAmount": 180.99,
        },
        {
          "productId": "CLOTH001",
          "productName": "Casual T-Shirt",
          "category": "Clothes",
          "quantity": 2,
          "price": 25.00,
          "description": "Comfortable and stylish casual t-shirt made from soft cotton fabric.",
          "status": "Shipped",
          "orderDate": "2023-08-15",
          "totalAmount": 350.99,
        },
        {
          "productId": "CLOTH002",
          "productName": "Slim Fit Jeans",
          "category": "Clothes",
          "quantity": 1,
          "price": 50.99,
          "description": "Modern slim fit jeans with a touch of stretch for flexibility and comfort.",
          "status": "Shipped",
          "orderDate": "2023-08-15",
          "totalAmount": 350.99,
        },
        {
          "productId": "CLOTH003",
          "productName": "Elegant Floral Dress",
          "category": "Clothes",
          "quantity": 1,
          "price": 150.75,
          "description": "A beautiful floral dress perfect for special occasions or a night out.",
          "status": "Delivered",
          "orderDate": "2023-08-14",
          "totalAmount": 150.75,
        },
        {
          "productId": "CLOTH008",
          "productName": "Summer Shorts",
          "category": "Clothes",
          "quantity": 1,
          "price": 75.25,
          "description": "Lightweight and comfortable shorts for a casual summer look.",
          "status": "Shipped",
          "orderDate": "2023-08-11",
          "totalAmount": 125.25,
        },
        {
          "productId": "CLOTH009",
          "productName": "Colorful Patterned Socks",
          "category": "Clothes",
          "quantity": 2,
          "price": 25.00,
          "description": "Playful and vibrant patterned socks to add a pop of color to your outfit.",
          "status": "Shipped",
          "orderDate": "2023-08-11",
          "totalAmount": 125.25,
        },
        {
          "productId": "CLOTH010",
          "productName": "Classic Fedora Hat",
          "category": "Clothes",
          "quantity": 1,
          "price": 30.99,
          "description": "Timeless and stylish fedora hat to complete your look.",
          "status": "Delivered",
          "orderDate": "2023-08-10",
          "totalAmount": 180.99,
        },
        {
          "productId": "CLOTH011",
          "productName": "Winter Gloves",
          "category": "Clothes",
          "quantity": 2,
          "price": 75.00,
          "description": "Warm and cozy winter gloves to keep your hands protected from the cold.",
          "status": "Delivered",
          "orderDate": "2023-08-10",
          "totalAmount": 180.99,
        },
    
        {
          "productId": "CLOTH004",
          "productName": "Stylish Leather Jacket",
          "category": "Clothes",
          "quantity": 1,
          "price": 100.00,
          "description": "Classic leather jacket with a modern twist, perfect for colder months.",
          "status": "Processing",
          "orderDate": "2023-08-13",
          "totalAmount": 300.00,
        },
        {
          "productId": "CLOTH005",
          "productName": "Printed Mini Skirt",
          "category": "Clothes",
          "quantity": 2,
          "price": 50.00,
          "description": "Playful and trendy printed mini skirt for a fun fashion statement.",
          "status": "Processing",
          "orderDate": "2023-08-13",
          "totalAmount": 300.00,
        }
      ,
        {
          "productId": "CLOTH012",
          "productName": "Classic Oxford Shirt",
          "category": "Clothes",
          "quantity": 1,
          "price": 95.50,
          "description": "Timeless oxford shirt with a classic fit, suitable for both formal and casual occasions.",
          "status": "Shipped",
          "orderDate": "2023-08-09",
          "totalAmount": 215.50,
        },
        {
          "productId": "CLOTH013",
          "productName": "Cotton Chinos",
          "category": "Clothes",
          "quantity": 1,
          "price": 120.00,
          "description": "Versatile cotton chinos with a comfortable fit, perfect for everyday wear.",
          "status": "Shipped",
          "orderDate": "2023-08-09",
          "totalAmount": 215.50,
        }
  ]
  